Hotfix/standardize documentation
Team-Micras/MicrasFirmware pull request #28
Opened 2024-12-28 03:00 UTC by GabrielCosme

Essa PR padroniza a documentação do Micras, e para isso, eu segui os seguintes conceitos:

1. Toda documentação deve estar em inglês e no imperativo;
2. Todas os métodos e atributos de classes devem estar documentados;
3. Sempre deve ter um ponto no final em cada bloco;
4. Todos blocos devem começar com letra maiúscula;
5. Os blocos tparam, param e return não devem ser separados por linhas vazias;
6. O bloco de return nunca deve explicitar o tipo do retorno;
7. Sempre que possível, os valores devem ter sua unidade explicita na documentação.

Para me ajudar no processo de padronização, eu escrevi alguns regex correspondentes a alguns dos pontos acima, vou deixá-los aqui em baixo para referência futura:

3. \* @(?!.*(\.|(file)))
4. @[^((\s)|(param))]+ [a-z]
4. @param [^\s]+ [a-z]
5.  +\*\n +\* @return
6. @return ((float)|(bool)|(uint)|(int)|(std))

2024-12-28 16:50 UTC, Eduardo-Barreto commented
![image](https://github.com/user-attachments/assets/fc9bbdeb-d33e-4869-a913-eee4056c1c90)
:pray:

2024-12-28 17:11 UTC, Eduardo-Barreto commented on include/micras/micras_controller.hpp
> +    ///@{
oq eh isso

2024-12-28 17:32 UTC, GabrielCosme commented on include/micras/micras_controller.hpp
> +    ///@{
Isso é o do doxygen, assim que faz pra definir um grupo de coisas, se não tivesse isso seria como se o comentário só tivesse na primeira coisa.

2024-12-28 17:49 UTC, Eduardo-Barreto approved these changes
to em duvida de algumas coisas mas o geral ta bem bala

muitos pontos literalmente

boa cosmos

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_core/include/micras/core/butterworth_filter.hpp
> + * @file
eu nunca entendi as motivações disso

eu ate entenderia se fosse "nao quero escrever" mas juro q nao entendo remover

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_hal/include/micras/hal/pwm.hpp
> +     * @note Changing the pwm frequency will also change the duty cycle and reset the counter.
n sei se `will also change the duty cycle` eh descritivo o suficiente. Se eu ler rapido no meio do debug posso inclusive assumir que "ah ok, ele ja resolve isso pra mim"

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_hal/include/micras/hal/timer.hpp
> +     * @return Time elapsed in miliseconds.
pq time elapsed e nao elapsed time? nao sei ingles

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_hal/src/pwm.cpp
> +    __HAL_TIM_SET_COUNTER(this->handle, 0);
23h59: standardize documentation
00h00:

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/follow_wall.hpp
>      float get_right_value() const;
pega o valor certo :nerd_face:

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/look_at_point.hpp
> +     * @param pose The current pose of the robot.
nao seria state?

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/look_at_point.hpp
> +     * @param pose The current pose of the robot.
state

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/state.hpp
>      float distance(const Point& other) const;
pq isso aq n eh um operador?

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_proxy/include/micras/proxy/argb.hpp
> +    ///@{
estructo

2024-12-28 17:49 UTC, Eduardo-Barreto commented on micras_proxy/src/buzzer.cpp
> +    this->pwm.set_duty_cycle(50.0F);
23h59
00h00:

2024-12-28 17:49 UTC, Eduardo-Barreto commented on .clang-tidy
> +  readability-function-cognitive-complexity.Threshold: 30
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk

2024-12-28 17:55 UTC, GabrielCosme commented on micras_core/include/micras/core/butterworth_filter.hpp
> + * @file
Isso não adiciona nenhuma informação, o nome do arquivo você sabe pq ta com ele aberto, e o doxygen também já sabe. E a data quase nunca ta correta, e o git é muito mais confiável pra saber quando alguma coisa foi modificada e quem modificou. Então tirei de todos pra criar um padrão no qual isso não é colocado, ai nos próximos arquivos eu não vou precisar escrever e não vou ficar me incomodando com datas erradas.

2024-12-28 17:56 UTC, GabrielCosme commented on .clang-tidy
> +  readability-function-cognitive-complexity.Threshold: 30
Shhhhhh kkkkkkk

2024-12-28 17:57 UTC, GabrielCosme commented on micras_nav/include/micras/nav/state.hpp
>      float distance(const Point& other) const;
Qual operador você recomendaria?

2024-12-28 18:00 UTC, GabrielCosme commented on micras_hal/include/micras/hal/timer.hpp
> +     * @return Time elapsed in miliseconds.
Acredito que os dois existem e estão certos, existe uma explicação histórica pra isso, mas não entendi nada.

2024-12-28 18:53 UTC, Eduardo-Barreto commented on micras_core/include/micras/core/butterworth_filter.hpp
> + * @file
eu gostava do brief do file mas acho q o da classe ta bom o suficiente

2024-12-28 18:54 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/state.hpp
>      float distance(const Point& other) const;
-

2024-12-28 18:54 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/state.hpp
>      float distance(const Point& other) const;
kkkkkkkk vsf virou um bullet point

`-`

2024-12-28 19:00 UTC, GabrielCosme commented on micras_nav/include/micras/nav/state.hpp
>      float distance(const Point& other) const;
Mas já tem o operador de - implementado ali embaixo, ele retorna um outro ponto

2024-12-30 18:00 UTC, dardengo requested changes
Muito bom. Nota 2.

2024-12-30 18:00 UTC, dardengo commented on include/micras/micras_controller.hpp
>       */
Seria legal informar o que cada valor significa.

2024-12-30 18:00 UTC, dardengo commented on include/micras/micras_controller.hpp
>       */
Seria legal informar o que cada valor significa.

2024-12-30 18:00 UTC, dardengo commented on include/micras/micras_controller.hpp
>       */
Seria legal informar o que cada valor significa.

2024-12-30 18:00 UTC, dardengo commented on include/micras/micras_controller.hpp
> +     * @param elapsed_time Time elapsed since the last run.
Em s, ms ou µs?

2024-12-30 18:00 UTC, dardengo commented on micras_core/include/micras/core/butterworth_filter.hpp
> +     * @brief Produces a new value from measured data.
Mudar para o imperativo "Produce".

2024-12-30 18:00 UTC, dardengo commented on micras_core/include/micras/core/utils.hpp
> + * @brief Create an array objects calling its constructors from an array of parameters.
Adicionar preposição entre "array" e "objects". Mudar "its" pra "their".

2024-12-30 18:00 UTC, dardengo commented on micras_core/include/micras/core/utils.hpp
> + * @brief Create an array objects calling its constructors from a single parameter.
Adicionar preposição entre "array" e "objects". Mudar "its" pra "their".

2024-12-30 18:00 UTC, dardengo commented on micras_hal/include/micras/hal/adc_dma.hpp
>      void start_dma(std::span<uint16_t> buffer);
N faria sentido colocar na doc a informação que diferencia as duas?

2024-12-30 18:00 UTC, dardengo commented on micras_hal/include/micras/hal/flash.hpp
>      static void read(uint16_t page, uint16_t page_address, uint64_t data[], uint32_t size = 1);
Add no brief a diferença das duas.

2024-12-30 18:00 UTC, dardengo commented on micras_hal/include/micras/hal/flash.hpp
>      static void write(uint16_t page, uint16_t page_address, const uint64_t data[], uint32_t size = 1);
Add no brief a diferença das duas.

2024-12-30 18:00 UTC, dardengo commented on micras_hal/include/micras/hal/mcu.hpp
> +     * @brief Initializes MCU and some peripherals.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_hal/src/mcu.cpp
> + * @brief Initializes System Clock.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @brief Resets the PID controller.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @brief Resets the base readings of the wall sensors.
Mudar para imperativo. Eu acho "Reset the wall sensors base readings" mais natural.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @brief Get the reading of the left wall sensor.
"from" em vez de "of" ou tb "Get the left wall sensor reading".

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @brief Get the reading of the right wall sensor.
"from" em vez de "of" ou tb "Get the right wall sensor reading".

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @return The reading of the left wall sensor.
"from" em vez de "of" ou tb "The left wall sensor reading."

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @return The reading of the right wall sensor.
"from" em vez de "of" ou tb "The right wall sensor reading."

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/go_to_point.hpp
> +     * @brief Calculates the command to go to a point.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/go_to_point.hpp
> +     * @brief Checks if the robot has reached the goal.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> + * @brief Converts an angle in radians to a Grid side.
Mudar para imperativo. "from" em vez de "in".

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Returns the direction from this point to the next one.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Moves in the grid in the direction of the side.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Compares two points for equality.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Returns the pose after moving forward.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Returns the pose after turning back.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Returns the pose after turning left.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Returns the pose after turning right.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/grid_pose.hpp
> +     * @brief Compares two poses for equality.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/look_at_point.hpp
> +     * @brief Calculates the command to look at a point.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/look_at_point.hpp
> +     * @brief Resets the PID controllers.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/look_at_point.hpp
> +     * @brief Checks if the robot has reached the goal.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/mapping.hpp
> +         * @brief Possible types of actions.
Seria interessante ter uma breve descrição de cada ação.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/mapping.hpp
> +     * @brief Check if the robot is at a distance from a wall at the front.
Eu diria que ele sempre vai estar a alguma distancia da parede.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/mapping.hpp
> +     * @brief Check if the robot is at a distance from a wall at the sides.
idem

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/mapping.hpp
> +     * @brief Adds diagonal movements to the best route.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Updates the maze walls with the current pose and new information.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Returns the next point the robot should go to when exploring.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Returns the next point the robot should go to when returning.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Checks the type of wall following the robot can do.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Checks whether the robot has finished the maze.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Checks whether the robot has returned to the start.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Calculates the best route to the goal using the current costmap.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Improves the route to the goal.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Returns the best route to the goal.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Checks whether there is a wall at the front of a given pose.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Calculates the costmap for the flood fill algorithm.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Returns the cell at the given position.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/maze.hpp
> +     * @brief Returns the cell at the given position.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/pid_controller.hpp
> + * @brief Implementation of simple PID controller. Response = kp * (error + hi * integral(error) kd * d/dt(error))
ki

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Calculates the distance to another point.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Calculates the angle between two points.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Converts the point to a grid point.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Rotates the point by a given angle.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Moves the point towards another point by a given distance.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Subtracts a point from another.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Compares two points for equality.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Calculates the remainder of the division of the point by a value.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Converts a grid point to a point.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Converts the pose to a grid pose.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_nav/include/micras/nav/state.hpp
> +     * @brief Converts the pose to a cell reference.
Mudar para imperativo.

2024-12-30 18:00 UTC, dardengo commented on micras_proxy/include/micras/proxy/rotary_sensor_reg.hpp
> + * @brief Registers class for the rotary sensor configuration.
struct

2024-12-30 18:00 UTC, dardengo commented on micras_proxy/include/micras/proxy/torque_sensors.hpp
> +     * @brief Construct a newTorqueSensors object.
Espaço dps de "new".

2024-12-30 18:00 UTC, dardengo commented on micras_proxy/include/micras/proxy/torque_sensors.hpp
> +     * @brief Get the current from the sensor.
add "reading" dps de "current" e a unidade.

2024-12-30 18:00 UTC, dardengo commented on micras_proxy/include/micras/proxy/wall_sensors.hpp
> +     * @brief Construct a newWallSensors object.
Espaço dps de "new".

2024-12-30 18:03 UTC, Eduardo-Barreto commented on micras_nav/include/micras/nav/pid_controller.hpp
> + * @brief Implementation of simple PID controller. Response = kp * (error + hi * integral(error) kd * d/dt(error))
ele tava dando oi e vc nao respondeu 

hi cosme

2024-12-30 19:43 UTC, GabrielCosme commented on micras_nav/include/micras/nav/follow_wall.hpp
> +     * @brief Resets the base readings of the wall sensors.
Eu concordo que em um texto realmente fica melhor, mas em comentários eu sinto que geralmente se usa muito essa estrutura, que ai você lê primeiro o que a coisa é e depois vem as características, ai acaba ficando mais dinâmico quando você só quer saber o que a função faz ou o que é a variável.

2024-12-30 19:44 UTC, GabrielCosme commented on micras_nav/include/micras/nav/grid_pose.hpp
> + * @brief Converts an angle in radians to a Grid side.
É que Grid side não é uma unidade de ângulo, ai a ideia é mais que ele pega um angulo que está em radianos em converte em um outro objeto.

2024-12-30 20:25 UTC, dardengo approved these changes
👌

2024-12-30 20:26 UTC, merged